In [4]:
import cv2
import numpy as np
from PIL import Image
import os
path = 'data/'
recognizer = cv2.face.LBPHFaceRecognizer_create()
detector = cv2.CascadeClassifier("haarcascade_frontalface_alt2.xml")
def getImagesAndLabels(path):
    imagePath = [os.path.join(path, f) for f in os.listdir(path)]
    faceSamples = []
    ids = []
    for imagePath in imagePath:
        PIL_img = Image.open(imagePath).convert('L')
        img_numpy = np.array(PIL_img, 'uint8')
        print(img_numpy)
        id = int(os.path.split(imagePath)[-1].split(".")[1])
        faces = detector.detectMultiScale(img_numpy)
        for (x,y,w,h) in faces:
            faceSamples.append(img_numpy[y:y + h, x:x + w])
            ids.append(id)
    return faceSamples, ids
print ("Пагади, пагади...")
faces,ids = getImagesAndLabels(path)
recognizer.train(faces, np.array(ids))
recognizer.write('model/trainer.yml')
print("{0} faces trained. Exiting Program".format(len(np.unique(ids))))

Пагади, пагади...
[[254 255 255 ... 202 211 217]
 [255 254 253 ... 188 204 213]
 [254 255 255 ... 176 194 205]
 ...
 [ 14  15  17 ...  31  32  33]
 [ 16  16  17 ...  31  33  35]
 [ 16  17  18 ...  32  33  34]]
[[222 219 219 ... 162 176 186]
 [220 218 216 ... 156 171 183]
 [217 222 223 ... 145 162 177]
 ...
 [ 16  15  15 ...  33  31  30]
 [ 15  15  15 ...  32  31  30]
 [ 15  15  15 ...  32  32  31]]
[[213 209 200 ... 147 163 180]
 [221 221 220 ... 144 156 173]
 [220 219 219 ... 143 145 157]
 ...
 [ 16  17  17 ...  31  33  34]
 [ 16  17  17 ...  33  35  36]
 [ 17  17  16 ...  35  37  38]]
[[255 255 255 ... 159 175 192]
 [246 244 244 ... 155 169 189]
 [198 196 194 ... 153 164 184]
 ...
 [ 17  15  14 ...  33  36  38]
 [ 15  14  13 ...  34  36  38]
 [ 14  13  13 ...  34  37  39]]
[[255 255 255 ... 207 217 226]
 [254 255 255 ... 195 211 222]
 [255 254 254 ... 183 205 217]
 ...
 [ 19  18  18 ...  37  39  41]
 [ 19  18  18 ...  37  39  41]
 [ 18  17  17 ...  35  36  37]]
[[212 213 209 ... 235 

[[220 222 230 ... 156 166 177]
 [219 218 221 ... 151 157 165]
 [242 236 230 ... 150 154 162]
 ...
 [ 19  19  19 ...  31  31  32]
 [ 20  20  20 ...  30  30  31]
 [ 20  20  20 ...  31  31  32]]
[[221 221 221 ... 184 192 224]
 [212 207 202 ... 179 194 216]
 [248 245 245 ... 173 194 206]
 ...
 [ 24  24  24 ...  38  38  36]
 [ 24  24  24 ...  37  37  37]
 [ 22  22  22 ...  37  37  37]]
[[223 226 239 ... 227 229 234]
 [219 216 221 ... 225 229 235]
 [248 243 240 ... 220 223 229]
 ...
 [ 19  19  20 ...  34  33  33]
 [ 18  18  19 ...  34  33  33]
 [ 18  18  19 ...  33  33  33]]
[[248 247 248 ... 165 178 190]
 [238 241 245 ... 162 175 185]
 [208 205 201 ... 160 175 188]
 ...
 [ 19  20  20 ...  31  30  31]
 [ 20  21  22 ...  31  31  32]
 [ 20  22  23 ...  31  32  33]]
[[249 249 248 ... 184 197 206]
 [230 233 236 ... 183 198 208]
 [219 220 220 ... 183 198 210]
 ...
 [ 21  22  23 ...  35  34  34]
 [ 21  22  23 ...  35  35  34]
 [ 22  23  23 ...  36  35  34]]
[[218 217 217 ... 230 234 234]
 [218 219

[[111 110 110 ...  71  71  71]
 [112 112 111 ...  71  71  72]
 [112 113 112 ...  73  73  73]
 ...
 [ 58  53  49 ...  44  46  47]
 [ 55  51  49 ...  45  47  48]
 [ 52  50  48 ...  44  46  48]]
[[255 255 255 ... 239 237 238]
 [254 254 254 ... 240 240 240]
 [255 255 255 ... 242 242 243]
 ...
 [ 14  15  15 ...  27  29  30]
 [ 14  14  15 ...  28  30  30]
 [ 14  15  16 ...  31  31  32]]
[[114 114 114 ...  73  73  73]
 [114 113 112 ...  73  72  71]
 [114 114 113 ...  76  74  72]
 ...
 [ 75  72  69 ...  54  54  56]
 [ 73  71  68 ...  53  54  56]
 [ 71  70  67 ...  51  52  54]]
[[115 114 113 ...  74  74  75]
 [111 111 112 ...  71  73  74]
 [109 110 110 ...  69  71  72]
 ...
 [ 67  67  67 ...  47  48  48]
 [ 67  66  66 ...  46  47  48]
 [ 67  67  66 ...  46  47  47]]
[[108 107 107 ...  73  73  73]
 [109 108 108 ...  73  73  74]
 [109 108 107 ...  74  74  74]
 ...
 [ 62  62  62 ...  43  45  46]
 [ 63  63  62 ...  43  45  46]
 [ 65  64  63 ...  42  45  46]]
[[108 107 107 ...  73  73  73]
 [109 108

 [103 103 104 ...  88  86  86]]
[[174 173 168 ... 143 144 146]
 [173 165 156 ... 143 143 143]
 [171 164 158 ... 148 147 147]
 ...
 [104 104 104 ...  86  86  85]
 [102 102 103 ...  86  85  85]
 [100 101 102 ...  85  85  85]]
[[136 135 152 ... 146 145 145]
 [129 138 158 ... 143 143 145]
 [132 145 159 ... 140 142 143]
 ...
 [ 95  97  98 ...  85  84  83]
 [ 94  96  97 ...  85  85  84]
 [ 93  95  97 ...  85  85  85]]
[[241 240 242 ... 146 146 146]
 [243 239 238 ... 143 143 142]
 [241 240 237 ... 142 142 143]
 ...
 [ 85  85  85 ...  86  85  85]
 [ 84  84  84 ...  87  86  85]
 [ 84  84  84 ...  88  87  86]]
[[240 245 247 ... 148 150 149]
 [241 248 248 ... 147 149 148]
 [242 250 248 ... 140 146 150]
 ...
 [ 92  93  93 ...  92  92  92]
 [ 93  93  93 ...  93  92  92]
 [ 94  94  94 ...  93  92  91]]
[[249 247 247 ...  96  96  97]
 [249 248 248 ...  97  97  97]
 [249 249 250 ...  97  97  97]
 ...
 [235 234 232 ...  97  98  98]
 [233 233 232 ...  97  97  98]
 [230 231 231 ...  97  97  97]]
[[250 25

 [ 92  92  90 ...  89  89  88]]
[[182 179 178 ... 141 150 150]
 [178 179 181 ... 140 149 153]
 [170 177 187 ... 139 147 154]
 ...
 [ 95  96  96 ...  79  83  86]
 [ 92  93  95 ...  73  79  82]
 [ 96  94  92 ...  70  76  80]]
[[219 210 191 ... 158 154 155]
 [218 198 182 ... 159 155 156]
 [220 193 180 ... 163 157 153]
 ...
 [ 92  91  90 ...  67  70  74]
 [ 92  91  90 ...  64  67  71]
 [ 91  90  90 ...  62  65  69]]
[[250 250 249 ... 103 106 107]
 [248 248 248 ... 101 104 106]
 [250 250 250 ... 100 104 106]
 ...
 [229 230 227 ...  68  70  71]
 [228 230 230 ...  67  68  69]
 [228 227 230 ...  66  67  67]]
[[237 229 212 ... 149 149 149]
 [235 229 214 ... 148 149 149]
 [234 227 213 ... 148 147 147]
 ...
 [ 98  98  98 ...  95  93  93]
 [ 96  99  97 ...  96  96  93]
 [ 95  97  96 ...  97  96  93]]
[[250 250 250 ... 111 114 116]
 [250 250 250 ... 107 109 111]
 [250 250 250 ... 105 106 108]
 ...
 [232 232 232 ...  61  61  61]
 [229 229 229 ...  61  61  61]
 [230 228 228 ...  61  60  60]]
[[250 25

[[241 241 241 ...  76  75  76]
 [240 241 241 ...  75  73  74]
 [239 240 241 ...  72  69  69]
 ...
 [229 229 229 ...   3   6   8]
 [229 229 229 ...   6   9  11]
 [230 229 229 ...   9  12  14]]
[[241 241 241 ...  82  78  75]
 [241 241 241 ...  77  73  70]
 [240 241 240 ...  78  73  69]
 ...
 [228 228 229 ...   9  13  17]
 [229 228 229 ...  12  16  19]
 [229 228 229 ...  14  18  22]]
[[242 242 242 ...  88  85  81]
 [241 241 241 ...  86  83  80]
 [242 242 241 ...  83  80  78]
 ...
 [228 227 228 ...   4   5   5]
 [229 228 228 ...   4   5   7]
 [228 227 228 ...   5   7   9]]
[[242 239 236 ...  84  83  81]
 [237 237 238 ...  83  79  77]
 [241 241 241 ...  81  78  76]
 ...
 [231 231 230 ...   9  12  13]
 [229 230 230 ...   9  12  15]
 [229 230 230 ...   9  15  18]]
[[242 243 243 ...  87  85  83]
 [242 241 240 ...  86  83  82]
 [243 241 239 ...  85  83  81]
 ...
 [231 232 232 ...   3   4   4]
 [228 230 232 ...   4   5   9]
 [230 231 231 ...   6   8  10]]
[[243 242 241 ...  86  81  78]
 [242 242

 [230 230 229 ...   0   1   1]]
[[237 234 236 ...  39  35  38]
 [235 237 236 ...  40  38  42]
 [235 240 239 ...  41  40  45]
 ...
 [231 230 228 ...   6  11  15]
 [229 228 227 ...  12  16  17]
 [226 226 227 ...  18  18  16]]
[[237 235 235 ...  49  45  45]
 [241 237 236 ...  48  45  44]
 [238 234 235 ...  48  46  46]
 ...
 [229 228 228 ...   0   0   0]
 [230 229 228 ...   1   1   1]
 [229 228 228 ...   1   2   2]]
[[241 238 237 ...  46  38  33]
 [240 238 236 ...  44  37  31]
 [237 236 236 ...  43  36  31]
 ...
 [230 230 230 ...   0   0   0]
 [229 229 229 ...   0   1   1]
 [229 229 229 ...   1   2   3]]
[[237 237 237 ...  63  59  53]
 [235 236 237 ...  60  56  50]
 [235 237 239 ...  56  53  47]
 ...
 [228 228 227 ...   1   1   1]
 [230 230 229 ...   1   1   1]
 [232 232 231 ...   1   1   1]]
[[237 237 237 ...  64  61  55]
 [236 237 237 ...  60  57  51]
 [236 237 238 ...  56  54  48]
 ...
 [231 230 230 ...   3   3   3]
 [226 226 227 ...   2   2   2]
 [227 227 227 ...   1   1   1]]
[[238 23